### ISSUE TITLE
BUG: fix WCAG issues in begrepskatalogen

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/catalog-frontend#150]
## 🐛 Bug rapport

https://begrepskatalog.staging.fellesdatakatalog.digdir.no/910244132

Bruk WAVE til å finne feilene. 

<img width="363" alt="image" src="https://github.com/Informasjonsforvaltning/catalog-frontend/assets/48259307/b64e79e4-b356-4b4b-a007-bf526077af86">

### Sjekkliste (Sjekk av etter issue er laget)

- [ ] Lagt til label(s)
- [ ] Lagt i utviklingsbrettet (Project)

**Comment by jeffreiffers** [comment]
1. Det er en label reference feil i Textarea komponenten fra designsystemet
2. Brødsmuler - Ikke klart i backend, kan fikses når det skal implementeres

**Comment by KjerstiSteien** [comment]
@jeffreiffers har vi meldt fra om wcagfeilen i Textarea til designsystemgjengen?

**Comment by KjerstiSteien** [comment]
Og er det laget egen sak på brødsmuler?

**Comment by jeffreiffers** [comment]
> @jeffreiffers har vi meldt fra om wcagfeilen i Textarea til designsystemgjengen? 

Usikker men kan gjøre det.

**Comment by jeffreiffers** [comment]
> Og er det laget egen sak på brødsmuler? 

Relatert til wcag tenker du?

**Comment by KjerstiSteien** [comment]
> > Og er det laget egen sak på brødsmuler?
> 
> Relatert til wcag tenker du?

Ja, og for å få brødsmuler inn i admingrensesnittet. Det hadde gjort testing lettere.
