### ISSUE TITLE
Epic(concept:endringsforslag): oversikt over alle endringsforslag

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/catalog-frontend#172]
## 🚀 Feature forespørsel
- [x] #185
- [x] #186
- [x] #187
- [x] #188
- [x] #203
- [x] #209

### Feature beskrivelse
En side med en liste som viser oversikt over alle endringsforslagene.

Figma: https://www.figma.com/file/CsZl0GuNdXtefq4KYGfPs9/Begrepskatalog?type=design&node-id=1%3A668&mode=design&t=AKGuax7Lp1Rxsouk-1
skjermbildet:
![bilde](https://github.com/Informasjonsforvaltning/catalog-frontend/assets/108797958/19648298-0218-4fb7-925f-859fbc26e618)

### Hvorfor trenger vi det?
se behov: https://github.com/Informasjonsforvaltning/behov/issues/886

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label for app: admin, concept, e.l.
- [x] Lagt i utviklingsbrettet (Project)

**Comment by pooriamehregan** [comment]
Fra @KjerstiSteien : Dette ønsker de at skal vises i listen over endringsforslag: Foreslått av, tidspunkt forslaget ble lagt inn, anbefalt term (vises allerede), publiseringstilstand for opprinnelig begrep, antall felt som er endret (hvis lett å fikse).

**Comment by terjesyl** [comment]
@KurtStian Kan testes

**Comment by terjesyl** [comment]
Testet. Har opprettet eget issue på banner som mangler custom design. Lukker denne saken som ferdig.
