### ISSUE TITLE
Epic(concept:forslag-detalj): se endringsforslag for et begrep.

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/catalog-frontend#174]
### Feature beskrivelse
- [x] #178
- [x] #179
- [x] #474
- [x] #175
- [x] #176
- [x] #177
- [x] #182
- [x] #183
- [x] #184
- [x] #180
- [x] #181

Visningen av endringsforslaget skal vises som redigeringsskjemaet for endringsforslag, men med alle input-felter i readOnly.

Trenger knapper for å
- godta forslag
- avslå forslag
- redigere forslag (går til redigeringsskjema)

![image](https://github.com/Informasjonsforvaltning/catalog-frontend/assets/108797958/9e4e04dd-1c64-4dc1-945e-69343c5c75da)

~En detaljside som er nesten identisk begrepsdetaljside, men skal vise detaljer rundt et endringsforslag, f.eks felt som er endret (forslag) med grønn farge.~

~I motsetning til begrepsdetaljside skal denne siden ha kun kommentarer nederst på siden og ikke versioner eller endringshistorikk.~

| Header | Brukere med skrivetilgang | Brukere med lesetilgang |
|--------|--------|--------|
| kan godta | ja | nei |
| kan avslå | ja | nei | 
| kan redigere | ja | ja | 
| kan foreslå endring | ja | ja | 

### Hvorfor trenger vi det?
se behov: https://github.com/Informasjonsforvaltning/behov/issues/886

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label for app: admin, concept, e.l.
- [x] Lagt i utviklingsbrettet (Project)

**Comment by KjerstiSteien** [comment]
@terjesyl har du en duplikat av denne saken, eller jobber du på denne? Det jeg lurer på er: kan saken lukkes eller flyttes til in progress?

**Comment by terjesyl** [comment]
Denne er under arbied. Har jo kommet noen endringer i krav og design, så jeg kan gå gjennom issuene og lukke de som ikke er relevant lenger.

**Comment by terjesyl** [comment]
@KjerstiSteien vurdere om denne kan lukkes nå?
