### ISSUE TITLE
feat(concept:forslag-detalj): knapper - Rediger, Godta, Avslå og Foreslå endring

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/catalog-frontend#178]
- [x] UI-knapper visningsside endringsforslag
- [x] Logikk:
  - [x] Godta
  - [x] Avslå
  - [x] Rediger (redirect)

- [x] UI: Foreslå endring (på detaljside begrep)
- [x] Logikk: endringsforslag på begrep

![image](https://github.com/Informasjonsforvaltning/catalog-frontend/assets/108797958/f985fea3-adb7-45d8-a0cb-39522cf633b7)

**Comment by terjesyl** [comment]
Rediger, Godta, Avslå skal ligge på detaljsiden for endringsforslag.

"Foreslå endring" skal være på detaljsiden for begrep.
