### ISSUE TITLE
feat(concept:forslag-detalj): tittel på endringsforslag

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/catalog-frontend#179]
Må gjøres for:
- [x] Endringsforslag (redigeringsskjema)
- [x] Forslag til nytt begrep
  - Skal stå "Forslag til nytt begrep"
- [x] Visningsside av et endringsforslag

![image](https://github.com/Informasjonsforvaltning/catalog-frontend/assets/50879748/65fc0fb7-1a86-4069-82d5-cf6203309b9e)

**Comment by terjesyl** [comment]
Bruke DetailsHeader slik at det blir likt som på detaljsiden for begrep?
