### ISSUE TITLE
feat(concept:forslag-detalj): språkvelger

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/catalog-frontend#180]
![image](https://github.com/Informasjonsforvaltning/catalog-frontend/assets/50879748/d278e988-e5b8-47c3-90dd-c6e0e4a0f219)

**Comment by KjerstiSteien** [comment]
@terjesyl lukkes siden vi dropper språkvalg for endringsforslag?

**Comment by terjesyl** [comment]
Jepp!
