### ISSUE TITLE
feat(concept:forslag): breadcrumbs

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/catalog-frontend#185]
![image](https://github.com/Informasjonsforvaltning/catalog-frontend/assets/50879748/657aea48-52df-41f2-9a83-bcce91c25fc8)

**Comment by terjesyl** [comment]
@pooriamehregan Er denne til listevisning av alle endringsforslag eller detaljvisning?

**Comment by pooriamehregan** [comment]
Begge skal ha brødsmulesti hvis jeg forstår deg riktig :)
