### ISSUE TITLE
feat(concept:forslag): knapp for å forslå endring

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/catalog-frontend#188]
![image](https://github.com/Informasjonsforvaltning/catalog-frontend/assets/50879748/54bba57f-3770-446e-bd4a-03eb7ea520a7)

**Comment by pooriamehregan** [comment]
Jepp! GUIen er ferdig, men logikken mangler :)

**Comment by terjesyl** [comment]
Ferdig implementert
