### ISSUE TITLE
BUG: Begrep - treffliste: "Nytt begrep"-knapp går til tom side

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/catalog-frontend#197]
### Nåværende oppførsel
Når jeg trykker på "Nytt begrep"-knappen på trefflistesiden i begrepskatalogen, kommer jeg til en tom side: https://begrepskatalog.staging.fellesdatakatalog.digdir.no/910244132/undefined/edit

### Forventet oppførsel
Når jeg trykker på  "Nytt begrep"-knappen på trefflistesiden i begrepskatalogen, forventer jeg å komme til registreringsskjemaet for begrep Eks: https://registrering-begrep.fellesdatakatalog.digdir.no/991825827/ef620152-c6fd-40cf-9531-bb250d0c868e

### Hvordan reprodusere?
* Gå til https://begrepskatalog.staging.fellesdatakatalog.digdir.no/910244132
* Velg "Nytt begrep"
<img width="668" alt="image" src="https://github.com/Informasjonsforvaltning/catalog-frontend/assets/110605570/2a5016e5-aaab-4313-ae82-88932b197761">

### Konsekvens: 
Stopper test av skrivebruker i staging. 

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label for app: admin, concept, e.l.
- [x] Lagt i utviklingsbrettet (Project)

**Comment by jeffreiffers** [comment]
Dette har sikkert med skrivetilgang å gjøre. Har lagt inn sjekk på tilgang.
