### ISSUE TITLE
feat(concept:forslag): erstatte test data med reelle data når backend er klar.

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/catalog-frontend#203]

**Comment by terjesyl** [comment]
@pooriamehregan i hvilken sammenheng var denne tenkt? Er det med tanke på mock-dataen som var i frontend-koden?

**Comment by pooriamehregan** [comment]
@terjesyl Ja, hukser da jeg startet med å vise oversikt over alle endringsforslag, så lagde jeg en liste med testdata. Det var disse jeg tenkte på :)

**Comment by terjesyl** [comment]
@pooriamehregan Ok! Nå hentes dataen fra backend, så denne saken kan lukkes da?:)

**Comment by pooriamehregan** [comment]
@terjesyl Jepp!
