### ISSUE TITLE
feat(concept: forslag): legg til gjenstående listekolonner

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/catalog-frontend#209]
Dette ønsker de at skal vises i listen over endringsforslag: 
- Foreslått av, 
- tidspunkt forslaget ble lagt inn, 
- anbefalt term (vises allerede) (venstrejuster tekst), 
- ~publiseringstilstand for opprinnelig begrep~
    - ~[trenger avklaring:] hva skal vises hvis det fins både et publisert begrep og et utkast til samme begrep?~

utelater i denne omgang (bestemt i møte med Hege, Nils Ove og Terje):
- antall felt som er endret (hvis lett å fikse).

**Comment by pooriamehregan** [comment]
Venter på skisse

**Comment by terjesyl** [comment]
@KjerstiSteien På publiseringstilstand, hva skal vises dersom det fins en publisert versjon og en upublisert versjon? Endringsforslag vil jo kun rette seg mot upublisert versjon, men det fins en publisert versjon.

**Comment by terjesyl** [comment]
@KjerstiSteien bump, se spørsmål over

**Comment by terjesyl** [comment]
Skiller ut behov for avklaring på publiseringstilstand i eget issue slik at denne saken kan lukkes. Se #363.
Alt annet er ferdigstilt.
