### ISSUE TITLE
BUG: Får ikke opprettet, lagret endringer eller slettet kodelister

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/catalog-frontend#230]
## 🐛 Bug rapport

Innlogget som testbruker Maud Gulliksen via id-porten. Sjekk om brukeren har riktige rettigheter.

### Nåværende oppførsel

1: 
Hva gjorde jeg?
* Trykker på opprett kodeliste

Hva skjedde?
* Kodelistene "ny kodeliste 7" og "ny kodeliste 8" åpnet seg.
* Det ble ikke opprettet en ny kodeliste. 

2: 
Hva gjorde jeg? 
* La inn endringer på kodeliste 7
* Valgte lagre endringer. 

Hva skjedde? 
* Ingenting. 
* Ved oppdatering av siden var endringene borte. 

3: 
Hva gjorde jeg? 
* Valgte slett kodeliste

Hva skjedde? 
*Fikk opp advarsel og bekreftet sletting
* Ved bekreftelse skjedde ingenting. 
* Ved oppdatering av siden var kodelisten jeg forsøkte å endre der fortsatt. 

### Forventet oppførsel

Forventer at jeg kan opprette, endre og slette kodelister når jeg har admintilgang

### Sjekkliste (Sjekk av etter issue er laget)

- [ ] Lagt til label for app: admin, concept, e.l.
- [ ] Lagt i utviklingsbrettet (Project)

**Comment by hegeaal** [comment]
Skyldes trolig bruker uten riktig tilgang. Brukere som ikke skal ha tilgang til siden vil nå havne på en 'no access' side.
