### ISSUE TITLE
Bug: Administrator har ikke tilgang til knappene "Nytt begrep" og "Importer begrep"

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/catalog-frontend#233]
## 🐛 Bug rapport
Testet med administrator-bruker Maud Gulliksen

### Nåværende oppførsel
Når jeg går inn i begrepskatalogen får jeg kun opp knappen "Se alle endringsforslag" på toppen av siden. 

### Forventet oppførsel
Jeg forventer å kunne se alle knapper som skrivebruker har tilgang til (Nytt begrep) eller de admin skal ha tilgang til (Importer begrep)

Husk å sjekke:
* At skrivebruker har tilgang til de samme funksjonene som lesebruker i tillegg til funksjoner som krever skrivebrukertilgang.
* At administrator har tilgang til de samme funksjonene som skrivebruker og lesebruker i tillegg til funksjoner som krever administratortilgang
* At superadministrator har tilgang til de samme funksjonene som administrator, skrivebruker og lesebruker i tillegg til funksjoner som krever superadministratortilgang.

### Hvordan reprodusere?
Logg inn som Maud Gulliksen.
Gå inn på treffliste. 
Se hvilke knapper som vises på toppen av siden. 

### Sjekkliste (Sjekk av etter issue er laget)

- [ ] Lagt til label for app: admin, concept, e.l.
- [ ] Lagt i utviklingsbrettet (Project)

**Comment by jeffreiffers** [comment]
Maud er system administrator og vi har blitt enig at den kun har lesetilgang til alle kataloger.

**Comment by jeffreiffers** [comment]
System admin skal kun ha lese tilgang. Lukker saken.
