### ISSUE TITLE
History tab content

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/catalog-frontend#24]
### Feature beskrivelse
En tab som viser endringshistorikk for en begrep.
![image](https://user-images.githubusercontent.com/50879748/228776126-b58050f1-8696-4594-8b7b-070cb21659c8.png)

Mulig dette finnes i catalog-gui-old, ref. https://github.com/Informasjonsforvaltning/catalog-frontend/issues/42. Se der for inspo

### Hvorfor trenger vi det?
Se behov: https://github.com/Informasjonsforvaltning/behov/issues/807

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by pooriamehregan** [comment]
**Avklaring**: Trenges det en "Endret fra" rad? Fordi den nest siste "Endret til"-raden viser allerede hva den er endret fra.

**Comment by KurtStian** [comment]
Brytes ned til mindre issues.

**Comment by hegeaal** [comment]
Henger dette sammen med #42? @pooriamehregan @KjerstiSteien

**Comment by pooriamehregan** [comment]
Tror ikke disse skal være blokkert lenger siden skjellet, altså layout, er på plass nå. Alle sider som lages under concept-catalog får automatisk den layouten, altså header og footer.

**Comment by hegeaal** [comment]
> Brytes ned til mindre issues.

Fant ut at det ikke er nødvendig å bryte ned i mindre issues likevel, så lar issuet stå som det er ☺️

**Comment by jeffreiffers** [comment]
Endringslogg vises ikke slik det er skissert. Det krever noe flere endringer i tjenesten for å slippe å gjøre for mye logikk i frontend.
