### ISSUE TITLE
Liste med (små) bugs i begrepskatalogen

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/catalog-frontend#298]
Detaljside
- [x] Fagområde må vises med alle nivåer i hierarkiet. Nå vises kun nederste nivå. Eks: https://begrepskatalog.staging.fellesdatakatalog.digdir.no/910298062/07e3553e-e90e-4a3d-8470-ff660d895e48 Logget inn som Maud Gulliksen. 
- [ ] #308
- [x] Noen interne felt vises i høyrekolonnen, uten at jeg forstår hvorfor. Eks "Den lange historien" på eksempelet over. Forventer at interne felt fra admingrensesnittet vises samlet i "hovedtabellen" på siden. 
- [x] Tildelt-feltet vises ikke. 
- [x] Forkortelse vises ikke på riktig sted.
- [x] Kilde for "Definisjon for almennheten" og "Definisjon for spesialister" (tidligere jurister) vises ikke. Forventer at dette vises  på samme måte som for definisjon, men der Definisjon for allmennheten og Definisjon for spesialister er plassert i tabellen.  
- [ ] #310
- [x] Ikke vis term gruppe om ikke den har innhold

**Comment by jeffreiffers** [comment]
Noen interne felt vises i høyrekolonnen, uten at jeg forstår hvorfor. Eks "Den lange historien" på eksempelet over. Forventer at interne felt fra admingrensesnittet vises samlet i "hovedtabellen" på siden.

I admin løsningen kan man selv velge hvor et interne felt skal vises. Enten hoved kolonne eller høyre kolonne.
