### ISSUE TITLE
Feature: Legge til header og footer for alle sidene til admingrensesnittet

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/catalog-frontend#33]
## 🚀 Feature forespørsel
Mulig dette ligger klart i monorepoet -> skal være likt for hele prosjektet. 

### Sjekkliste (Sjekk av etter issue er laget)

- [ ] Lagt til label(s)
- [ ] Lagt i utviklingsbrettet (Project)

**Comment by pooriamehregan** [comment]
Første punkt løses av en layout-component som skal lages i ui-bibliotektet i monorepoet.
løses av https://github.com/Informasjonsforvaltning/catalog-frontend/issues/43

**Comment by pooriamehregan** [comment]
Punkt nr to løses når arbeidet med admingrensesnittet starter.

**Comment by hegeaal** [comment]
Allerede løst 👆
