### ISSUE TITLE
feat(concept:changeRequest): språkvalg på redigeringsside må flyttes

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/catalog-frontend#364]
## 🚀 Feature forespørsel
Språkvalg for skjema må flyttes til venstre for skjema og være flytende.

**Comment by KjerstiSteien** [comment]
@terjesyl kan denne lukkes nå som vi dropper språkvalg?

**Comment by terjesyl** [comment]
Jepp! Lukker saken
