### ISSUE TITLE
BUG: feilvarsel når det ikke er gjort endringer

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/catalog-frontend#393]
Hvis en trykker på Lagre-knappen uten at det er gjort endringer på en kodeliste, vises varselet:
<img width="333" alt="image" src="https://github.com/Informasjonsforvaltning/catalog-frontend/assets/48251060/30211749-a6e0-41fc-b834-0c398d270a56">

Så lenge det ikke er gjort noen endringer bør Lagre-knappen være skyggelagt/deaktivert

**Comment by hegeaal** [comment]
Allerede løst slik 👇 (Dette gjelder hele løsningen så blir litt omfattende å skrive om til å deaktivert lagre-knapp, spesielt mtp. kompleksiteten i kodelister-skjemaet). 

![image](https://github.com/Informasjonsforvaltning/catalog-frontend/assets/48259307/522705c4-a1c6-485e-95ff-16d9ceca5ad8)
