### ISSUE TITLE
BUG: Page users "Liste over brukernavn" nextjs oppgradering

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/catalog-frontend#403]
- [x] Kan ikke redigere navn
- [x] Kan ikke redigere epost
- [x] Ingenting skjer når jeg trykker på "Legg til nytt brukernavn"
- [x] Lagre og slett knapp er ikke sidestilt
- [x] Får ikke feilmelding når jeg prøver å slette og det ikke går
- [x] Får ikke feilmelding om at det ikke går ann å lagre (burde stå noe ala "du kan ikke lagre fordi det er ingen endringer"
- [x] Kan ikke slette
- [x] Kan ikke lagre

**Comment by pooriamehregan** [comment]
Tror feilene er fisket. Kjekt om du hadde mulighet til å teste på nytt :) Muligens fiskene også løser issues som er funnet andre steder i admin.
