### ISSUE TITLE
Feature: Flytt endringslogg fra gammel gui til ny front end

### ISSUE THREAD

**Issue by MrFranzen** [Informasjonsforvaltning/catalog-frontend#42]
## 🚀 Feature forespørsel

Blokkert av #25 

Flytt endringslogg når det er klart på gammel gui til dette nye repo

### Feature beskrivelse
Skal flytte endringslogg over på dette repo da all nyutvikling skjer her

### Hvorfor trenger vi det?
Fordi dette er nye stedet for front end til catalog gui

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by terjesyl** [comment]
Klart til å tas tak i.

**Comment by hegeaal** [comment]
Det finnes et annet issue for dette, #24
