### ISSUE TITLE
BUG: Dersom man står på en page som er høyere enn det søketreffet er får man ingen treff i begrepskatalog

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/catalog-frontend#424]
### Forventet oppførsel
Forventer å få treff på filter selv om jeg står på side 5 i katalogen

### Hvordan reprodusere?
1) Gå til begrepskatalog
2) Bla til side f.eks. 5
3) Sette på et filter (som du vet du skal få treff på)
4) Får ingen treff

### Sjekkliste (Sjekk av etter issue er laget)

- [ ] Lagt til label for app: admin, concept, e.l.
- [ ] Lagt i utviklingsbrettet (Project)

**Comment by jeffreiffers** [comment]
@hegeaal kan jeg lukke denne?

**Comment by hegeaal** [comment]
> @hegeaal kan jeg lukke denne?

Jepp!
