### ISSUE TITLE
changeRequest: vise tekstboks (Alert i designsystem) som forklarer skjema og feltene som ikke vises der men som er del av et begrep.

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/catalog-frontend#474]
Må gjøres på

- [x] Redigeringsskjema for endringsforslag.
- [x] Visningsside for endringsforslag/forslag til nytt begrep

![image](https://github.com/Informasjonsforvaltning/catalog-frontend/assets/108797958/2691627e-1d87-4173-ba56-7adc81481e8d)

**Comment by KjerstiSteien** [comment]
@terjesyl trenger dere tekst her?

**Comment by terjesyl** [comment]
Jepp, trenger tekst/konkret hva som skal stå der. Dere velger selv hvor mange linjer dere vil ha, Alert-boksen kan inneholde også bare én linje.
