### ISSUE TITLE
BUG: controlled/uncrontrolled error for filter som er lagt til via "internal fields" i admin

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/catalog-frontend#480]
Gjenskape: Trykk på et av filterene som er lagt til via interne felter i admin (type boolean i interne felt)

![image](https://github.com/Informasjonsforvaltning/catalog-frontend/assets/48259307/09ec454e-273d-4a7f-bda3-5b03cd09678c)

**Comment by NilsOveTen** [comment]
@hegeaal jeg klarer ikke å gjenskape, er dette fortsatt reelt?

**Comment by hegeaal** [comment]
> @hegeaal jeg klarer ikke å gjenskape, er dette fortsatt reelt?

Nope, ser ut til å være fikset 🤩
