### ISSUE TITLE
BUG: icon prop på Button er deprekert

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/catalog-frontend#541]
## 🐛 Bug rapport
Gjelder Button fra designsystemet. Må passes som children

`@deprecated — This will be changed to a boolean in the future to toggle icon only styling, icons will be passed as children`

- [ ] Lagt til label for app: admin, concept, e.l.
- [ ] Lagt i utviklingsbrettet (Project)

**Comment by hegeaal** [comment]
Fikset ved oppdatering av designsystemet
