### ISSUE TITLE
BUG: Feil tjenestestatus farger

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/catalog-frontend#553]
### Nåværende oppførsel
Alle status farger i tjenestekatalogen har like farger.

### Forventet oppførsel
Ulike farger skal vises for forskjellige statuser.

### Hvordan reprodusere?
Logg inn til tjenstekatalogen og sjekke statusfargene i trefflista.

### Forslag/Løsning [Valgfritt]
Status fargene kan defineres i språk-filen og deretter hentes som key-value til tjenestekatalogen. Sjekk f.eks.hvordan det er løst for  begrepstatus

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label for app: admin, concept, e.l.
- [x] Lagt i utviklingsbrettet (Project)

**Comment by pooriamehregan** [comment]
Venter på at @matfuru oppdaterer skissene med stausfarger.

**Comment by matfuru** [comment]
Her er oppdaterte statusfarger: https://www.figma.com/file/CsZl0GuNdXtefq4KYGfPs9/Begrepskatalog?type=design&node-id=1%3A668&mode=design&t=ckMDBzcZglPyYF11-1

**Comment by matfuru** [comment]
Oppdatert lenke med statuser og farger: https://www.figma.com/file/guff4Yy7fridJnPHglAsrr/Reg.-l%C3%B8sning-for-tjenester-og-hendelser?type=design&node-id=0%3A1&mode=design&t=87q5OOD4Hy88HQsK-1
