### ISSUE TITLE
BUG: Det er mulig å foreslå nytt begrep uten å oppgi anbefalt term, og da kan man ikke åpne endringsforslaget etterpå

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/catalog-frontend#562]
### Nåværende oppførsel

Det er mulig å foreslå nytt begrep uten å legge inn anbefalt term. Hvis det gjøres er det heller ikke mulig å åpne forslaget da termen er lenken for å åpne forslaget:
![image](https://github.com/Informasjonsforvaltning/catalog-frontend/assets/43232700/291c59b3-01ac-4ad0-af0d-f51272eb7e66)

### Forventet oppførsel

Man skal få feilmelding hvis anbefalt term ikke er oppgitt. Endringsforslag skal ikke opprettes. Ev. kan dette løses ved at det legges på en term (f.eks. Uten term) eller at man endrer hva som er lenken til endringsforslaget.

Bør få feilmelding hvis det

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label for app: admin, concept, e.l.
- [x] Lagt i utviklingsbrettet (Project)

**Comment by terjesyl** [comment]
@KjerstiSteien Hva tenker du om løsning her? Skal vi introdusere skjema-validering?

**Comment by terjesyl** [comment]
Gjør først en fiks som viser "Uten tittel" eller noe sånt, slik at man kan åpne endringsforslaget.

**Comment by terjesyl** [comment]
Om vi ønsker validering i skjemaet kan det tas som egen feature forespørsel

**Comment by KjerstiSteien** [comment]
Lagde også et behov for validering av skjema for nytt begrep. Må også verifiseres som behov før vi tar tak i det. https://github.com/Informasjonsforvaltning/behov/issues/960
