### ISSUE TITLE
[UX]: Merking av avnittsoverskrifter når man lagrer "Forslag til nytt begrep" er ikke hensiktmessig

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/catalog-frontend#568]
### Nåværende oppførsel

Når man oppretter "Forslagt til nytt begrep" blir avnittsoverskriften til felt som blir fylt ut i skjemaet merket "gult" og med tekst. 

### Dette er et problem fordi:
Første gang man oppretter det nye forslaget så finnes det ikke noen opplysninger fra før slik at jeg mener det blir feil å merke de som endret.

**Comment by terjesyl** [comment]
Bug, Forslag til nytt begrep skal ikke vise endringer i forhold til (ikke-eksisterende) originalt begrep
