### ISSUE TITLE
[Bug]: Ikke mulig å klikke på begreper under Versjoner

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/catalog-frontend#601]
### Nåværende oppførsel
Ikke mulig å klikke på lenker til versjoner av begrep under "Versjon"-fanen nederst på detaljsiden, fordi fanen hopper til "Kommentar".

### Forventet oppførsel
At Versjoner fortsatt vises selv om man hovrer over begreps-lenkene.

### Hvordan reprodusere?
Testet i Firefox 122.0.

- Gå inn på detaljside til begrep (eks: https://begrepskatalog.staging.fellesdatakatalog.digdir.no/910244132/1da1041f-435f-4563-8145-1707fba74c22)
- Bla til nederst på siden og klikk på "Versjoner"
- Flytt musepekeren over en av "Transportportal.no"-lenkene/begrepene.
- Fanevalget hopper nå tilbake til "Kommentarer"

![image](https://github.com/Informasjonsforvaltning/catalog-frontend/assets/108797958/702f6f44-6d05-4346-8448-e68ee24b85bd)

![image](https://github.com/Informasjonsforvaltning/catalog-frontend/assets/108797958/8733d9c4-de81-4652-8dc8-3c1980c94037)

**Comment by jeffreiffers** [comment]
Virker som denne har blitt løst. Lukker saken.
