### ISSUE TITLE
[Bug]: publiseringstilstand sier "Publisert i Felles Datakatalog null"

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/catalog-frontend#626]
### Nåværende oppførsel
Publiseringstilstand viser null-verdi, det står "Publisert i Felles Datakatalog null"
![image](https://github.com/Informasjonsforvaltning/catalog-frontend/assets/108797958/8507244d-f283-4826-95a6-ef07e42584be)

### Forventet oppførsel
Skal det stå dato her? Ev. ingenting om publiseringsdato er ukjent (`null`)?

### Hvordan reprodusere?
Besøk for eksempel begrepet "data.norge.no" under RAMSUND OG ROGNAN REVISJON.

**Comment by hegeaal** [comment]
Løst av: https://github.com/Informasjonsforvaltning/catalog-frontend/commit/102bbec96669245e2e7663e9268363be5f65cdaf
