### ISSUE TITLE
[Bug]: Rediger-knapp har usynlig tekst i tjenestekatalogen

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/catalog-frontend#640]
### Nåværende oppførsel
Redigerknappen på detaljsiden til en tjeneste viser ingen synlig tekst. Når jeg hovrer over med musepeker ser jeg teksten Rediger svakt i samme farge som knappen

![image](https://github.com/Informasjonsforvaltning/catalog-frontend/assets/110605570/4383e5dd-215a-4980-83af-a306045c83eb)

### Forventet oppførsel
Forventer at redigeringsknappen har synlig tekst "redigering", slik den vises i begrepskatalogen

![image](https://github.com/Informasjonsforvaltning/catalog-frontend/assets/110605570/c9387cb8-ba6e-4851-b6d0-e2cdb0ab245c)

### Hvordan reprodusere?
Gå inn på registrer.demo.fellesdatakatalog.digdir.no
Logg inn som Stein Eidem
Gå inn på tjenestekatalogen til Høgskolen for IT og arkitektur
Gå inn på tjenesten Eplesyre
Se på redigeringsknappen.

**Comment by hegeaal** [comment]
Fikset ved oppdatering av designsystem
