### ISSUE TITLE
[Bug]: Forbedre auth og permissions

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/catalog-frontend#659]
### Nåværende oppførsel
Forbedre auth og permissions

### Områder som er testet ok
- Logg inn med bank id til hovedside registreringsløsning. 
- Logg inn med bank id til et spesifikt begrep
- Sende inn endringsforslag som lesebruker
- Registrere nytt begrep Virksomhetsadmin
- Redigere begrep virksomhetsadmin
- Publisere begrep virksomhetsadmin
- Administrasjonsgrensesnitt: endre design
- Administrasjonsgrensesnitt: legge til bruker i liste over brukere
- Administrasjonsgrensesnitt: Endre bruker i liste over brukere

### Feil funnet i test: 
- [x] Lesebruker og skrivebruker: "Logg ut" vises ikke når jeg trykker på navnet mitt oppe i høyre hjørne. Testet med Stein Eidem.

**Comment by pooriamehregan** [comment]
Test nå admin- og begrepskatalogen og alt så ut til å fungere ok, untatt det som dere har allerede oppdaget. 

Ellers ble spurt om å logge inn via Keycloack men kom inn etter jeg trykket på knappen. Jeg logget da først inn med chrome og ikke logget ut, men lukket vinduet. Så logget inn med safari -med samme bruker (Michelle)- så dukket knappen opp . Men denne har jeg også sett før dine endringer her, vet ikke om det er relevant eller viktig for denne pren?!
