### ISSUE TITLE
Vis publiseringsdato på detaljesiden til begrep

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/catalog-frontend#84]
Feltet for publiseringsdato skal vise dato og klokkeslett for publisering

![Screenshot from 2023-06-14 15-11-52](https://github.com/Informasjonsforvaltning/catalog-frontend/assets/50194012/c32ba044-d167-4cd8-8aac-b874110541d6)

Dato kan hentes fra feltet `publiseringsTidspunkt` fra backend

**Comment by KjerstiSteien** [comment]
Skal denne saken egentlig hete "vis publiseringstilstand på detaljesiden til begrep"? Den er knyttet opp til brukerhistorie for publiseringstilstand.

**Comment by jeffreiffers** [comment]
Publiser skal få eget endepunkt i concept-catalog og concept skal få eget publiseringsdato felt. Publisering skal ikke være del av endringshistorikken og derfor heller med i jsonpatches.
